### ISSUE TITLE
Fake Issue

### ISSUE THREAD

**Issue by cyanidecupcake** [MakerBox-NZ/pygame_liam#2]
You currently have no bugs in your code. This is a fake issue to help you learn how to view and close issues.

Now that you've read this issue you can close it and erase your name from the whiteboard.

**Comment by ackerto983** [comment]
da tux is back with a new weapon to poltergiest the lonely woman who need da lot of money basically going to dem damm bank and get it take it home give it to your damn kids they don't give a damn of a sumo wrestler that lives in da town of bread that wants to give money to Emma Hellking!!!!! this is another public service annoucement brought to you by da tux!!!!!!!
